import { useEffect, useRef, useState, type ReactNode } from "react";
import InteractiveBiology from "./labs/InteractiveBiology";
import InteractiveChemistry from "./labs/InteractiveChemistry";

type Subject="Physics"|"Chemistry"|"Biology";
type Lab={id:string;subject:Subject;title:string;description:string;icon:string};
const labs:Lab[]=[
{id:"projectile",subject:"Physics",title:"Projectile Motion",description:"Test launch speed, angle and gravity and watch the trajectory respond.",icon:"↗"},
{id:"newton",subject:"Physics",title:"Newton's Laws",description:"Apply force to a mass and observe acceleration and friction.",icon:"→"},
{id:"ohm",subject:"Physics",title:"Ohm's Law",description:"Build a simple circuit and explore voltage, resistance and current.",icon:"Ω"},
{id:"optics",subject:"Physics",title:"Lens & Ray Optics",description:"Move an object around a converging lens and construct its image.",icon:"◉"},
{id:"waves",subject:"Physics",title:"Waves & Sound",description:"Change amplitude and frequency and observe a travelling wave.",icon:"∿"},
{id:"atom",subject:"Chemistry",title:"Atomic Structure",description:"Explore protons, neutrons, electrons and shell arrangement.",icon:"⚛"},
{id:"bonding",subject:"Chemistry",title:"Chemical Bonding",description:"See valence electrons share or transfer to form bonds.",icon:"↔"},
{id:"reaction",subject:"Chemistry",title:"Reaction Rate",description:"Test temperature and concentration through collision theory.",icon:"✦"},
{id:"ph",subject:"Chemistry",title:"Acids & Bases",description:"Mix acid and base and observe the changing pH.",icon:"pH"},
{id:"electrolysis",subject:"Chemistry",title:"Electrolysis",description:"Watch ions migrate through an electrolyte toward electrodes.",icon:"⚡"},
{id:"cell",subject:"Biology",title:"Cell Explorer",description:"Inspect organelles inside an interactive animal or plant cell.",icon:"◎"},
{id:"heart",subject:"Biology",title:"Human Heart",description:"Follow blood through the four chambers, valves and vessels.",icon:"♥"},
{id:"lungs",subject:"Biology",title:"Respiratory System",description:"Trace air through branching airways to alveoli and gas exchange.",icon:"◌"},
{id:"neuron",subject:"Biology",title:"Neuron & Reflex Arc",description:"Trace an electrical impulse from dendrites along an axon to the synapse.",icon:"⌁"},
{id:"photosynthesis",subject:"Biology",title:"Photosynthesis",description:"Manipulate light, CO₂ and water and observe the limiting input.",icon:"☀"}
];
const clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));
function useCanvas(draw:(ctx:CanvasRenderingContext2D,w:number,h:number,t:number)=>void,deps:unknown[]){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const el=ref.current;if(!el)return;let raf=0,t=0;const frame=()=>{t+=1/60;const d=Math.min(devicePixelRatio||1,2),w=el.clientWidth,h=el.clientHeight;if(el.width!==w*d||el.height!==h*d){el.width=w*d;el.height=h*d}const ctx=el.getContext("2d");if(!ctx)return;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);draw(ctx,w,h,t);raf=requestAnimationFrame(frame)};frame();return()=>cancelAnimationFrame(raf)},deps);return ref}
function Grid({ctx,w,h}:{ctx:CanvasRenderingContext2D;w:number;h:number}){ctx.strokeStyle="#e8ebef";ctx.lineWidth=1;for(let x=0;x<w;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}}
function Range({label,value,min,max,step=1,onChange,unit=""}:{label:string;value:number;min:number;max:number;step?:number;onChange:(v:number)=>void;unit?:string}){return <label className="control"><span>{label}<b>{value}{unit}</b></span><input type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(+e.target.value)}/></label>}
function Stage({children,controls,readout}:{children:ReactNode;controls?:ReactNode;readout?:ReactNode}){return <div className="lab-stage"><div className="visual">{children}</div>{readout&&<div className="readout">{readout}</div>}{controls&&<div className="controls">{controls}</div>}</div>}

function ProjectileLab(){const[speed,setSpeed]=useState(24),[angle,setAngle]=useState(45),[g,setG]=useState(9.8);const range=speed*speed*Math.sin(2*angle*Math.PI/180)/g;const ref=useCanvas((ctx,w,h)=>{Grid({ctx,w,h});const a=angle*Math.PI/180,maxY=speed*speed*Math.sin(a)**2/(2*g),scale=Math.min((w-70)/Math.max(range,1),(h-70)/Math.max(maxY,1))*.8;ctx.strokeStyle="#5662d9";ctx.lineWidth=4;ctx.beginPath();for(let x=0;x<=range;x+=Math.max(range/100,.01)){const y=x*Math.tan(a)-g*x*x/(2*speed*speed*Math.cos(a)**2),px=35+x*scale,py=h-30-y*scale;x?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.stroke();ctx.fillStyle="#111";ctx.beginPath();ctx.arc(35,h-30,6,0,7);ctx.fill()},[speed,angle,g]);return <Stage readout={<>Range <b>{range.toFixed(1)} m</b> · Maximum height <b>{(speed*speed*Math.sin(angle*Math.PI/180)**2/(2*g)).toFixed(1)} m</b></>} controls={<><Range label="Launch speed" value={speed} min={5} max={50} onChange={setSpeed} unit=" m/s"/><Range label="Launch angle" value={angle} min={5} max={85} onChange={setAngle} unit="°"/><Range label="Gravity" value={g} min={1} max={20} step={.1} onChange={setG} unit=" m/s²"/></>}><canvas ref={ref}/></Stage>}

function PhysicsLab({id}:{id:string}){const[a,setA]=useState(id==="waves"?35:id==="ohm"?6:id==="optics"?80:30),[b,setB]=useState(id==="waves"?2:id==="ohm"?10:id==="optics"?80:5),[c,setC]=useState(id==="newton"?4:5);const ref=useCanvas((ctx,w,h,t)=>{Grid({ctx,w,h});ctx.strokeStyle="#5662d9";ctx.lineWidth=4;if(id==="newton"){const acc=Math.max(0,(a-c)/Math.max(b,1));const x=30+(acc*t*t*18)%(w-100);ctx.fillStyle="#5662d9";ctx.fillRect(x,h/2-28,56,56);ctx.fillStyle="#111";ctx.font="15px system-ui";ctx.fillText("F = ma",x+9,h/2+5)}else if(id==="ohm"){const current=a/Math.max(b,.1);ctx.strokeStyle="#111";ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(60,h/2);ctx.lineTo(w*.32,h/2);ctx.lineTo(w*.38,h/2-45);ctx.lineTo(w*.62,h/2-45);ctx.lineTo(w*.68,h/2);ctx.lineTo(w-60,h/2);ctx.lineTo(w-60,h/2+60);ctx.lineTo(60,h/2+60);ctx.closePath();ctx.stroke();ctx.fillStyle="#111";ctx.font="16px system-ui";ctx.fillText("I = "+current.toFixed(2)+" A",70,h/2+95)}else if(id==="optics"){const cx=w/2,cy=h/2,focus=b;ctx.strokeStyle="#111";ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(cx,25);ctx.lineTo(cx,h-25);ctx.stroke();ctx.fillStyle="#111";ctx.fillRect(Math.max(35,cx-a),cy-55,7,55);ctx.strokeStyle="#5662d9";ctx.lineWidth=2;for(const yy of [cy-55,cy-25]){ctx.beginPath();ctx.moveTo(Math.max(42,cx-a),yy);ctx.lineTo(cx,yy);ctx.lineTo(cx+focus,cy);ctx.stroke()}ctx.fillStyle="#111";ctx.beginPath();ctx.arc(cx-focus,cy,5,0,7);ctx.arc(cx+focus,cy,5,0,7);ctx.fill()}else{ctx.beginPath();for(let x=0;x<w;x+=2){const y=h/2+a*Math.sin(x*.012*b-t*3);x?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke()}},[id,a,b,c]);const labels=id==="newton"?["Force","Mass","Friction"]:id==="ohm"?["Voltage","Resistance","Load"]:id==="optics"?["Object distance","Focal length","Ray height"]:["Amplitude","Frequency","Wave speed"];return <Stage readout={id==="newton"?<>Acceleration <b>{Math.max(0,(a-c)/Math.max(b,1)).toFixed(2)} m/s²</b> · Newton's second law</>:id==="ohm"?<>Current <b>{(a/Math.max(b,.1)).toFixed(2)} A</b> · Power <b>{(a*a/Math.max(b,.1)).toFixed(1)} W</b></>:id==="optics"?<>Focal length <b>{b}</b> · The ray construction changes as the object moves.</>:<>Amplitude <b>{a}</b> · Frequency <b>{b}</b> Hz · Period <b>{(1/Math.max(b,.1)).toFixed(2)} s</b></>} controls={<><Range label={labels[0]} value={a} min={id==="newton"?0:id==="ohm"?1:id==="optics"?30:5} max={id==="newton"?60:id==="ohm"?12:id==="optics"?180:70} onChange={setA} unit={id==="ohm"?" V":id==="newton"?" N":""}/><Range label={labels[1]} value={b} min={id==="newton"?1:id==="ohm"?1:id==="optics"?30:.5} max={id==="newton"?20:id==="ohm"?30:id==="optics"?140:5} step={id==="waves"?.1:1} onChange={setB} unit={id==="ohm"?" Ω":id==="newton"?" kg":id==="waves"?" Hz":""}/><Range label={labels[2]} value={c} min={0} max={id==="newton"?20:100} onChange={setC}/></>}><canvas ref={ref}/></Stage>}

function LabSimulation({lab}:{lab:Lab}){if(lab.id==="projectile")return <ProjectileLab/>;if(lab.subject==="Physics")return <PhysicsLab id={lab.id}/>;if(lab.subject==="Chemistry")return <InteractiveChemistry id={lab.id}/>;return <InteractiveBiology id={lab.id}/>}

export default function App(){const[subject,setSubject]=useState<Subject|"All">("All"),[active,setActive]=useState<Lab|null>(null);const filters=["All","Physics","Chemistry","Biology"] as const;const visible=labs.filter(l=>subject==="All"||l.subject===subject);return <main><header><button className="brand" onClick={()=>setActive(null)}><span className="mark">S</span><span><strong>Soren Labs</strong><small>Interactive science for students</small></span></button><nav>{filters.map(x=><button className={subject===x?"active":""} onClick={()=>setSubject(x)} key={x}>{x}</button>)}</nav></header>{active?<section className="lab-page"><button className="back" onClick={()=>setActive(null)}>← All Labs</button><div className="lab-head"><span className="pill">{active.subject}</span><h1>{active.title}</h1><p>{active.description}</p></div><LabSimulation lab={active}/><div className="learn"><h2>Explore → Observe → Understand</h2><p>These models are designed around the mechanism itself: change a variable, watch matter or signals move, and connect the observation to the science.</p></div></section>:<><section className="hero"><span className="eyebrow">SOREN LABS · 15 INTERACTIVE EXPERIMENTS</span><h1>Learn science by <em>testing it.</em></h1><p>Interactive Physics, Chemistry and Biology experiments where the visual model responds to what you change.</p></section><div className="filters">{filters.map(x=><button className={subject===x?"active":""} onClick={()=>setSubject(x)} key={x}>{x}</button>)}</div><section className="grid">{visible.map(l=><article className="card" key={l.id} onClick={()=>setActive(l)}><div className="icon">{l.icon}</div><span>{l.subject}</span><h2>{l.title}</h2><p>{l.description}</p><button>Open Lab →</button></article>)}</section></>}</main>}
